### ISSUE TITLE
Typo in cmake variable

### ISSUE THREAD

**Issue by traits** [simulton/gpds#1]
https://github.com/simulton/GPDS/blob/2ff0467347de3c0f7f1cbf1fe7edbcbc8b9b67b8/lib/CMakeLists.txt#L48

**Comment by Tectu** [comment]
Thanks for spotting & reporting this.
Do you want to provide a PR for this or shall we just patch it on our end?

**Comment by traits** [comment]
Too small, patch it in. I will come back with more significant things, I hope :)
