### ISSUE TITLE
_deps\gpds-src\lib\include\gpds\utils.hpp(41): error C2039: 'to_string': is not a member of 'std'

### ISSUE THREAD

**Issue by aboelens** [simulton/gpds#15]
Building gpds I get the followinf error message:

_deps\gpds-src\lib\include\gpds\utils.hpp(41): error C2039: 'to_string': is not a member of 'std'

Adding "#include <string>" to utils.hpp fixes the issue.

Version: 1.6.0 (for version 1.5.0 of QSchematic)
Compiler: MSVC
OS: Windows 10
Building method: CMake in PowerShell

**Comment by Tectu** [comment]
Fixed - Thank you for reporting this!
