### ISSUE TITLE
ninja: error: CMakeFiles/impl-Debug.ninja:566: multiple rules generate _deps/gpds-build/lib/Debug/gpdsd.lib

### ISSUE THREAD

**Issue by aboelens** [simulton/gpds#16]
Related to issue:

https://github.com/simulton/QSchematic/issues/50

I also get this error massage for gpds when I try to build gpds for QSchematic 1.5.0 on windows 10 in PowerShell:

ninja: error: CMakeFiles/impl-Debug.ninja:566: multiple rules generate _deps/gpds-build/lib/Debug/gpdsd.lib

Thanks,

Arnout

**Comment by Tectu** [comment]
This should be fixed in the current `master` branch.
Can you please check?

**Comment by Tectu** [comment]
The `1.8.0` release should address this based on what I can see. Please feel free to re-open if that is not the case.

Basically, we introduced the CMake options `GPDS_BUILD_STATIC` and `GPDS_BUILD_SHARED` which allow to individually control which library type is being built. Furthermore, the CMake script will automatically default to only building the shared library when MSVC is used and it will error if both are enabled.

Thank you for reporting this!
