### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by cailtin** [simulton/gpds#4]
after doing: git submodule update --init --recursive

created a build dir, cmake ..

/home/clopez/third_party/workflow/GPDS/lib/include/gpds/archiver.hpp:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>

is missing a dependency? if so could you provide me the name of the dependencies, and may be update the documentation?

thanks

**Comment by Tectu** [comment]
There are no dependencies that wouldn't ship with the library directly. The only dependency really is tinyxml2 and that ships with the library.

It seems like `#include <filesystem>` isn't working. The filesystem library was added with C++17. Are you using a C++17 compatible compiler?

**Comment by cailtin** [comment]
Thanks  for your quick response, so now I need to figure what the problem is with my build.

Thanks again

**Comment by Tectu** [comment]
No worries - don't hesitate to ask if there are any questions.

The gist is that this should compile out of the box on any system with a C++17 capable compiler (and STL).
As of today, this library is being built successfully on WIndows, Linux, MacOS and FreeBSD with GCC and Clang.

**Comment by cailtin** [comment]
Thanks a lot: figured what the issue is: I am using open suse 15.2 which default compiler is gcc-7
In the past I just modified the .basrc and set the CC and CCX but it seems that cmake ignores the env. variables.
To solve: modified the CMakeCache.txt to use the gcc-10 and problem solved. 

And because I modified the .bashrc I did not checked which compiler cmake was using 

I have the lib build without any issues.

P.S the problem was that if I search for filesystem I found several headers, so I did not know which one to use.

Thanks and Tectu (what that means)

**Comment by Tectu** [comment]
> To solve: modified the CMakeCache.txt to use the gcc-10 and problem solved.

That is a _very_ bad idea. You should simply set `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` accordingly like so:
```shell
git clone https://github.com/simulton/gpds
cd gpds
mkdir build
cmake -S . -B build -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
```
CMake will print out which compiler(s) it is using during the configuration stage. You can simply have a look at the first couple of lines of output.

By the way: If you're looking for a library that goes a step further than GPDS and automatically serializes members, you can have a look at https://github.com/Tectu/cpp-properties 
It allows serializing to/from JSON & XML as well as GPDS containers.
Just in case that that is more of what you're looking for.

**Comment by cailtin** [comment]
Thanks a lot: I tried that but somewhere the cache file still had gcc-7, that is the reason that I modified the cache (and is not a bad idea, only if I ran cmake again :)

Thanks and I going to check your repo
